### ISSUE TITLE
XML Layout for Sign Up Activity

### ISSUE THREAD

**Issue by Agrim2112** [bsoc-bitbyte/myLeave#2]
Create the XML layout for Sign Up Activity based on the design provided in the [Figma](https://www.figma.com/design/jYm7XGidk1L3HNf9e4Otwn/myLeave?node-id=6-18&t=HjrOtyAfoLbxQDPn-1). 

Your layout must follow these guidelines:

1. Use Constraint Layout to ensure the layout is responsive to all screen sizes.
1. Adhere to the given Figma design
2. Follow the specified naming convention for each view group ID to maintain consistency and clarity.

**Comment by ayushsaksena30** [comment]
@Agrim2112 Please assign me this issue. My approach will be to add text views to display text and text edit for input and also use background as a drawable to get rounded button input.

**Comment by sujalagrawal2** [comment]
@Agrim2112 I'd like to take on this issue. My approach will be to add card view (for rounded corner) and inside it I will use constraint layout (so that layout is responsive). I will use TextView, EditText (for input) ,buttons. I will follow specified naming convention for each view group ID. 
Please assign it to me.
Thank You.

**Comment by Agrim2112** [comment]
@sujalagrawal2 You can take up the issue
